[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = 'light'

# Primary accent color for interactive elements.
primaryColor =  '#eb606c'
secondaryColor =  '#506788'

# Background color for the main content area.
backgroundColor = '#ffffff'
secondaryBackgroundColor = '#e8f3f4'

# Color used for almost all text.
textColor = '#42445a'

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = 'sans serif'